### ISSUE TITLE
Multiple ComfoConnect LAN C bridges not working

### ISSUE THREAD

**Issue by Wijnstra** [michaelarnauts/aiocomfoconnect#3] opened 2023-04-02 18:58 UTC
When configuring multiple ComfoConnect LAN bridges ( I have 2... ) the units aren't working both. 
Instead only 1 unit is controllable.

![image](https://user-images.githubusercontent.com/115800102/229373139-00d5c8b0-3c08-4bd5-9beb-a5a16cc340fa.png)

I hope you can help me out here...

**Comment by michaelarnauts** [comment] 2023-04-06 06:33
Duplicate of https://github.com/michaelarnauts/home-assistant-comfoconnect/issues/10

**Closed by michaelarnauts** 2023-04-06 06:33 UTC
